protectedBranches:
- name: master
  tag: latest
  level: major
  dependencies:
    "@zowe/perf-timing": latest
  aliasTags:
  - zowe-v1-lts
# - name: zowe-v1-lts
#   tag: ${name}
#   level: minor
#   dependencies:
#     "@zowe/perf-timing": ${name}
- name: 'lts-*'
  tag: ${name}
  level: patch
  dependencies:
    "@zowe/perf-timing": ${name}
