name: Test

on: [push, pull_request]

jobs:
  test:
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '[ci skip]')
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest]

    env:
      OS: ${{ matrix.os }}
      NODE: ${{ matrix.node-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Use NPM v7
      id: npm7
      run: npm install -g npm@^7

    - name: Install NPM Dependencies
      id: install
      run: npm ci

    - name: Update NPM Dependencies
      id: update
      uses: t1m0thyj/update-npm-deps@master

    - name: Build Source
      id: build
      run: npm run build --if-present

    - name: Unit Tests
      id: test
      run: npm run test || true
