name: Zowe CLI CI

on: [push, pull_request]

jobs:
  test:
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '[ci skip]')
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm ci

    - name: Update Dependencies
      uses: octorelease/run-script@master
      with:
        script: npmUpdate

    - name: Build Source
      id: build
      run: npm run build --if-present

    - name: Unit Tests
      id: test
      run: npm run test || true

  release:
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[ci skip]')
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
        ref: ${{ github.ref }}

    - name: Use Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'

    - name: Install Dependencies
      run: npm ci

    - name: Update Dependencies
      uses: octorelease/run-script@master
      env:
        GIT_COMMITTER_NAME: zowe-robot
        GIT_COMMITTER_EMAIL: zowe.robot@gmail.com
      with:
        script: npmUpdate

    - name: Build Source
      run: npm run build --if-present

    - uses: octorelease/octorelease@master
      env:
        GIT_COMMITTER_NAME: zowe-robot
        GIT_COMMITTER_EMAIL: zowe.robot@gmail.com
        GIT_CREDENTIALS: x-access-token:${{ secrets.ADMIN_GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
