name: Zowe CLI CI

on: [push, pull_request]

jobs:
  test:
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '[ci skip]')
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest]

    env:
      OS: ${{ matrix.os }}
      NODE: ${{ matrix.node-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Use NPM v7
      id: npm7
      run: npm install -g npm@^7

    - name: Install NPM Dependencies
      id: install
      run: npm ci

    # - name: Update NPM Dependencies
    #   id: update
    #   uses: t1m0thyj/node-versioner@master
    #   with:
    #     actions: update

    - name: Build Source
      id: build
      run: npm run build --if-present

    - name: Unit Tests
      id: test
      run: npm run test || true

  publish:
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[ci skip]')
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}

    - name: Use Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'

    - run: npm ci
      id: install

    # - uses: t1m0thyj/node-versioner@master
    #   id: update
    #   with:
    #     actions: update
    #     commit-updates: true
    #     git-committer-name: zowe-robot
    #     git-committer-email: zowe.robot@gmail.com

    - run: npm run build --if-present
      id: build

    - name: Checkout Octorelease
      uses: actions/checkout@v2
      with:
        repository: octorelease/octorelease
        path: octorelease

    - name: Build Plugins
      run: cd octorelease && npm ci && npm run build

    - uses: octorelease/octorelease@master
      env:
        GIT_COMMITTER_NAME: zowe-robot
        GIT_COMMITTER_EMAIL: zowe.robot@gmail.com
        GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
