name: Zowe CLI CI

on:
  push:
  pull_request:
    types: [closed, opened, synchronize, reopened]

jobs:
  test:
    # Run this job on push in original repo or pull request from forks.
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [windows-latest, ubuntu-latest, macos-latest]

    env:
      OS: ${{ matrix.os }}
      NODE: ${{ matrix.node-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Use NPM v7
      id: npm7
      run: npm install -g npm@^7

    - name: Install NPM Dependencies
      id: install
      run: npm ci

    - name: Update NPM Dependencies
      id: update
      uses: t1m0thyj/update-npm-deps@master

    - name: Build Source
      id: build
      run: npm run build --if-present

    - name: Unit Tests
      id: test
      run: npm run test || true

  publish:
    # Do not run this job on forks or when PR is opened.
    if: (github.repository == 't1m0thyj/zowe-deploy-test' && github.event.pull_request.action == 'closed' && github.event.pull_request.merged)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - run: npm ci

    - uses: t1m0thyj/update-npm-deps@master
      env:
        GIT_COMMITTER_NAME: zowe-robot
        GIT_COMMITTER_EMAIL: zowe.robot@gmail.com
      with:
        commit: true

    - run: npm run build --if-present

    - name: Semantic Release
      run: npx semantic-release-zowe-cli
      env:
        GIT_AUTHOR_NAME: zowe-robot
        GIT_AUTHOR_EMAIL: zowe.robot@gmail.com
        GIT_COMMITTER_NAME: zowe-robot
        GIT_COMMITTER_EMAIL: zowe.robot@gmail.com
        GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
