name: Zowe CLI CI

on: [push, pull_request]

jobs:
  test:
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '[ci skip]')
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest]

    env:
      OS: ${{ matrix.os }}
      NODE: ${{ matrix.node-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Use NPM v7
      id: npm7
      run: npm install -g npm@^7

    - name: Install NPM Dependencies
      id: install
      run: npm ci

    - name: Update NPM Dependencies
      id: update
      uses: t1m0thyj/node-versioner@master
      with:
        actions: update

    - name: Build Source
      id: build
      run: npm run build --if-present

    - name: Unit Tests
      id: test
      run: npm run test || true

  publish:
    if: github.event_name == 'push' && github.repository == 't1m0thyj/zowe-deploy-test' && !contains(github.event.head_commit.message, '[ci skip]')
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - run: git pull --depth=0 --no-rebase

    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x

    - name: Use NPM v7
      id: npm7
      run: npm install -g npm@^7

    - run: npm ci
      id: install

    - uses: t1m0thyj/node-versioner@master
      id: update
      with:
        actions: update
        commit-updates: true
        git-committer-name: zowe-robot
        git-committer-email: zowe.robot@gmail.com

    - run: npm run build --if-present
      id: build

    - uses: t1m0thyj/node-versioner@master
      id: version
      with:
        actions: version
        git-committer-name: zowe-robot
        git-committer-email: zowe.robot@gmail.com
        github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

    - uses: t1m0thyj/node-versioner@master
      id: publish
      with:
        actions: publish
        github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        npm-token: ${{ secrets.NPM_TOKEN }}
